Name:           ros-lunar-iot-bridge
Version:        0.9.0
Release:        0%{?dist}
Summary:        ROS iot_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/iot_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       python-requests
Requires:       ros-lunar-diagnostic-msgs
Requires:       ros-lunar-rospy
Requires:       ros-lunar-rostopic
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-diagnostic-msgs
BuildRequires:  ros-lunar-rostest

%description
The iot_bridge provides a bi-directional bridge between ROS and the OpenHAB Home
Automation system. This allows a ROS robot to connect to a vast variety of IoT
devices such as motion detectors, Z-Wave devices, lighting, door locks, etc.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sat Jun 17 2017 mike <corb@aol.com> - 0.9.0-0
- Autogenerated by Bloom

